language: python
python:
- 3.6
sudo: required
install:
- nvm install 10
- nvm use 10
- pip install transifex-client
- npm install
- npm install -g @angular/cli@7.1.3
script:
- ". extract_i18n.sh"
- tx push --source
- tx pull --mode sourceastranslation -l ar,en,am,ru
- python tools/yaml_to_json.py
deploy:
  skip_cleanup: true
  provider: script
  script: "./travis_deploy.sh"
  on:
    branch: master
env:
  global:
    secure: f1DoA5eG+F8tRDgFb15ANBwT2mwi2fH8KkeMuHgr8uj1MVc7OGxeJCkdX5MxsS6Ad1BceraQr9If19IIsdNcO+YyFhH6iPzBpLJ8vMJeItskYbfT+nBq9wzBUD7m8ixDeXlKE9R7VOPArGZpBJbLhqlksp+AQE33VfJD+pYBwqMDmbTjlo9hUigUa6EGzDLRYlcysgc56QZVlstzoOmiFPXjNybQ+Ng6nisduh7LW6GNSJf5HcS1Wf1udWjgT3dvXAaMY3vn9x8WtmSsHo/h1QFEN71SzPbw3rlUR8/lyIbDRFgE/Ryph7+3GITKbNE6OTLX2qorbabrfl5GW3RZAUvLWwW6aedXv5EDDCuDj+vVeBr3/fTkET1Xur3eiep1XjrFP6U+a6znJM3RkOI+7NQXN1OnQXHR/Lve4EM0TXlKXDGjP7mQt/xWsVT6X6qAjpLW1GMHFiokJXRmuj9lmXUIvLU/fCowLN6QcFpXSuXX3x1fBmf/0rvrSZNMMh2XU252oRu8L5B+EXhxAgzRuR9rfRITHT6eIb8NExLSKI8Yh7K82SCyyr1T9JVK5rp+nL6Jwg8UeTBZV8Nku3ZwG+V1UyOtCVJ4VHmhOEh9FNgwxKdiClidHnjX1JoqfPleyTdsnHDs5udSFMgVA1swSAftp7MLV0wUVBICXeDMf6U=
