language: python
python:
- 3.6
sudo: required
install:
- nvm install 10
- nvm use 10
- pip install transifex-client
- npm install
- npm install -g @angular/cli@7.1.3
script:
- ". extract_i18n.sh"
- tx push --source
- tx pull --mode sourceastranslation -l ar,en,am,ru
- python tools/yaml_to_json.py
deploy:
  skip_cleanup: true
  provider: script
  script: "./travis_deploy.sh"
  on:
    branch: master
env:
  global:
    secure: G0f4Y8FIkJCx3HsixH4eIBFIM9NReZHWHqu3dhM5vimmo9vGmSO0VkJteqfmz46d7cJ9lAFFTYyJtsftDG8X+9Gs9uw93Q0w1O1So00pX27+IF0G18Jow/jIiB2YTQ5LGwwk0Z0npJvwgK1JgmnjVVln0Q2gddcJirhTGY9ZGsXFiGReA3vjNvQJ+LUf+XzlKJuX+HbDLK5hey3Jb8V5keOTAmZLA3tCNr9BMwmh5UvyMdWj1uj/ztNNcnqw9QUd348zI+HTSwIFI5ujWtvc+ggPLQMDC7Bxsf+TXw6Dx7S4Fw+khNn/PwSIxDvI/iIzp5MxyvzyAExrulEEz2Mk9GqP0u63JrcFUZILcHUlhPmq2tZh3fDAugnf1+YyKyCFBx3L//baIXFMTblzaXhK6dNUCHFIGmun3Sh1vCauCHo9EfFslmaS64pofSICT5kAQS92yFW/KvOSCvwKlYQtAcw8Jx6+Xmod4lnyznZJhR7dIdaYkZE13Vfw3Ld1bLBKVI3KdNiQxi37Gf9wZpKD40dG22GnHgqcaaCD4Lc+Kj3YLCSb7FZ+N/QHgtMlkhw7qo05+AW/CjKbZ7A9dSOLQFVFqIa5VqWHZzI/e+siKmI1/p99k4awkYjwGZOdIHwucE3ciFoNWSNG51d17dbqkBzQfcyWMMe4752u0VeSuGc=
